### ISSUE TITLE
Onboarding needs some improvements

### ISSUE THREAD

**Issue by cearum** [michaelkremenetsky/Refeed#2]
When I put in my email to sign up it gave me a little piece of text saying "check your email". I thought there was an issue because my email address was still in the form. Maybe something like, "Email has been sent with more information, please check your email inbox", and clear the form. 

I also prefer a password and not have to go to my email every time I need to login.

Logging in doesn't seem to work either. I get the link. I follow the link. It has me put in my email. I check my email AGAIN. That one works. The first time I was able to get in, it logged me out forcing me to the previous steps again (two emails and finally in again).

**Comment by michaelkremenetsky** [comment]
Hey @cearum so sorry about this. I've added a new message at https://github.com/michaelkremenetsky/Refeed/commit/1f438868dc16c4d4c3f7a4f04183254cffd7a177.

I'm not a fan of passwords personally but I see where you coming from preferring a password option. It would require a pretty sizeable refactor of the auth system so I don't think it's worth it for now but I'll consider adding the option if enough people ask for it.

The link that's sent to your email box should automatically log you in on the browser you open it in. Let me know if it's still causing issues and I'll have more of a look at it.
