### ISSUE TITLE
supabase

### ISSUE THREAD

**Issue by Famku** [michaelkremenetsky/Refeed#5]
Hi,

is supabase mandatory as database, or is it possible use a lighter database like postgresql for self hosting?

**Comment by michaelkremenetsky** [comment]
Supabase uses PostgreSQL under the hood. It just provides functionality that we need such as authentication. Shouldn't be any heavier than raw postgres.

**Comment by Famku** [comment]
ok, I will try that with supabase

**Comment by Leopere** [comment]
why not include supabase as a part of the stack then?  this looks pretty great but I'm not sure I want to deploy a supabase instance I just want an rss reader that's modern.
